package main

import "github.com/logrusorgru/aurora"

const (
	FILE = iota
	DIR
	SYMLINK
	BROKEN
	ARCHIVE
	EXECUTABLE
	CODE
	IMAGE
	AUDIO
	VIDEO
)

var colorScheme = map[int]aurora.Color{
	FILE:       aurora.GreenFg,
	DIR:        aurora.BlueFg + aurora.BoldFm,
	SYMLINK:    aurora.CyanFg + aurora.UnderlineFm,
	BROKEN:     aurora.BlackFg + aurora.RedBg,
	ARCHIVE:    aurora.RedFg + aurora.UnderlineFm,
	EXECUTABLE: aurora.RedFg + aurora.BoldFm,
	CODE:       aurora.MagentaFg,
	IMAGE:      aurora.YellowFg,
	AUDIO:      aurora.YellowFg + aurora.BoldFm,
	VIDEO:      aurora.YellowFg,
}

var extensionToCategory = map[string]int{
	".7z":   ARCHIVE,
	".a":    ARCHIVE,
	".apk":  ARCHIVE,
	".ar":   ARCHIVE,
	".bz2":  ARCHIVE,
	".cab":  ARCHIVE,
	".cpio": ARCHIVE,
	".deb":  ARCHIVE,
	".dmg":  ARCHIVE,
	".egg":  ARCHIVE,
	".gz":   ARCHIVE,
	".iso":  ARCHIVE,
	".jar":  ARCHIVE,
	".lha":  ARCHIVE,
	".mar":  ARCHIVE,
	".pak":  ARCHIVE,
	".pea":  ARCHIVE,
	".rar":  ARCHIVE,
	".rpm":  ARCHIVE,
	".s7z":  ARCHIVE,
	".shar": ARCHIVE,
	".tar":  ARCHIVE,
	".tbz2": ARCHIVE,
	".tgz":  ARCHIVE,
	".tlz":  ARCHIVE,
	".war":  ARCHIVE,
	".whl":  ARCHIVE,
	".xpi":  ARCHIVE,
	".xz":   ARCHIVE,
	".zip":  ARCHIVE,
	".zipx": ARCHIVE,

	".bat": EXECUTABLE,
	".exe": EXECUTABLE,
	".msi": EXECUTABLE,

	".c":         CODE,
	".cc":        CODE,
	".class":     CODE,
	".clj":       CODE,
	".cljc":      CODE,
	".cljs":      CODE,
	".coffee":    CODE,
	".cp":        CODE,
	".cpp":       CODE,
	".cs":        CODE,
	".csproj":    CODE,
	".css":       CODE,
	".csx":       CODE,
	".cxx":       CODE,
	".d":         CODE,
	".dart":      CODE,
	".diff":      CODE,
	".el":        CODE,
	".gd":        CODE,
	".go":        CODE,
	".h":         CODE,
	".html":      CODE,
	".ipynb":     CODE,
	".java":      CODE,
	".js":        CODE,
	".lua":       CODE,
	".m":         CODE,
	".m4":        CODE,
	".patch":     CODE,
	".php":       CODE,
	".pl":        CODE,
	".po":        CODE,
	".py":        CODE,
	".rb":        CODE,
	".rs":        CODE,
	".sh":        CODE,
	".swift":     CODE,
	".vb":        CODE,
	".vcxproj":   CODE,
	".vue":       CODE,
	".xcodeproj": CODE,
	".xml":       CODE,

	".3dm":  IMAGE,
	".3ds":  IMAGE,
	".ai":   IMAGE,
	".bmp":  IMAGE,
	".dds":  IMAGE,
	".dwg":  IMAGE,
	".dxf":  IMAGE,
	".eps":  IMAGE,
	".gif":  IMAGE,
	".gpx":  IMAGE,
	".jpeg": IMAGE,
	".jpg":  IMAGE,
	".kml":  IMAGE,
	".kmz":  IMAGE,
	".max":  IMAGE,
	".png":  IMAGE,
	".ps":   IMAGE,
	".psd":  IMAGE,
	".svg":  IMAGE,
	".tga":  IMAGE,
	".thm":  IMAGE,
	".tif":  IMAGE,
	".tiff": IMAGE,
	".webp": IMAGE,
	".xcf":  IMAGE,

	".aac":  AUDIO,
	".aiff": AUDIO,
	".ape":  AUDIO,
	".au":   AUDIO,
	".flac": AUDIO,
	".gsm":  AUDIO,
	".it":   AUDIO,
	".m3u":  AUDIO,
	".m4a":  AUDIO,
	".mid":  AUDIO,
	".mp3":  AUDIO,
	".mpa":  AUDIO,
	".pls":  AUDIO,
	".ra":   AUDIO,
	".s3m":  AUDIO,
	".sid":  AUDIO,
	".wav":  AUDIO,
	".wma":  AUDIO,
	".xm":   AUDIO,

	".3g2":   VIDEO,
	".3gp":   VIDEO,
	".aaf":   VIDEO,
	".asf":   VIDEO,
	".avchd": VIDEO,
	".avi":   VIDEO,
	".drc":   VIDEO,
	".flv":   VIDEO,
	".m2v":   VIDEO,
	".m4p":   VIDEO,
	".m4v":   VIDEO,
	".mkv":   VIDEO,
	".mng":   VIDEO,
	".mov":   VIDEO,
	".mp2":   VIDEO,
	".mp4":   VIDEO,
	".mpe":   VIDEO,
	".mpeg":  VIDEO,
	".mpg":   VIDEO,
	".mpv":   VIDEO,
	".mxf":   VIDEO,
	".nsv":   VIDEO,
	".ogg":   VIDEO,
	".ogm":   VIDEO,
	".ogv":   VIDEO,
	".qt":    VIDEO,
	".rm":    VIDEO,
	".rmvb":  VIDEO,
	".roq":   VIDEO,
	".srt":   VIDEO,
	".svi":   VIDEO,
	".vob":   VIDEO,
	".webm":  VIDEO,
	".wmv":   VIDEO,
	".yuv":   VIDEO,
}
