package category

const (
	Dir = iota
	File
	Symlink
	Broken
	Archive
	Executable
	Code
	Image
	Audio
	Video
)

var Extensions = map[string]int{
	".7z":   Archive,
	".a":    Archive,
	".apk":  Archive,
	".ar":   Archive,
	".bz2":  Archive,
	".cab":  Archive,
	".cpio": Archive,
	".deb":  Archive,
	".dmg":  Archive,
	".egg":  Archive,
	".gz":   Archive,
	".iso":  Archive,
	".jar":  Archive,
	".lha":  Archive,
	".mar":  Archive,
	".pak":  Archive,
	".pea":  Archive,
	".rar":  Archive,
	".rpm":  Archive,
	".s7z":  Archive,
	".shar": Archive,
	".tar":  Archive,
	".tbz2": Archive,
	".tgz":  Archive,
	".tlz":  Archive,
	".war":  Archive,
	".whl":  Archive,
	".xpi":  Archive,
	".xz":   Archive,
	".zip":  Archive,
	".zipx": Archive,

	".bat": Executable,
	".exe": Executable,
	".msi": Executable,

	".c":         Code,
	".cc":        Code,
	".class":     Code,
	".clj":       Code,
	".cljc":      Code,
	".cljs":      Code,
	".coffee":    Code,
	".cp":        Code,
	".cpp":       Code,
	".cs":        Code,
	".csproj":    Code,
	".css":       Code,
	".csx":       Code,
	".cxx":       Code,
	".d":         Code,
	".dart":      Code,
	".diff":      Code,
	".el":        Code,
	".gd":        Code,
	".go":        Code,
	".h":         Code,
	".html":      Code,
	".ipynb":     Code,
	".java":      Code,
	".js":        Code,
	".lua":       Code,
	".m":         Code,
	".m4":        Code,
	".patch":     Code,
	".php":       Code,
	".pl":        Code,
	".po":        Code,
	".py":        Code,
	".rb":        Code,
	".rs":        Code,
	".sh":        Code,
	".swift":     Code,
	".vb":        Code,
	".vcxproj":   Code,
	".vue":       Code,
	".xcodeproj": Code,
	".xml":       Code,

	".3dm":  Image,
	".3ds":  Image,
	".ai":   Image,
	".bmp":  Image,
	".dds":  Image,
	".dwg":  Image,
	".dxf":  Image,
	".eps":  Image,
	".gif":  Image,
	".gpx":  Image,
	".jpeg": Image,
	".jpg":  Image,
	".kml":  Image,
	".kmz":  Image,
	".max":  Image,
	".png":  Image,
	".ps":   Image,
	".psd":  Image,
	".svg":  Image,
	".tga":  Image,
	".thm":  Image,
	".tif":  Image,
	".tiff": Image,
	".webp": Image,
	".xcf":  Image,

	".aac":  Audio,
	".aiff": Audio,
	".ape":  Audio,
	".au":   Audio,
	".flac": Audio,
	".gsm":  Audio,
	".it":   Audio,
	".m3u":  Audio,
	".m4a":  Audio,
	".mid":  Audio,
	".mp3":  Audio,
	".mpa":  Audio,
	".pls":  Audio,
	".ra":   Audio,
	".s3m":  Audio,
	".sid":  Audio,
	".wav":  Audio,
	".wma":  Audio,
	".xm":   Audio,

	".3g2":   Video,
	".3gp":   Video,
	".aaf":   Video,
	".asf":   Video,
	".avchd": Video,
	".avi":   Video,
	".drc":   Video,
	".flv":   Video,
	".m2v":   Video,
	".m4p":   Video,
	".m4v":   Video,
	".mkv":   Video,
	".mng":   Video,
	".mov":   Video,
	".mp2":   Video,
	".mp4":   Video,
	".mpe":   Video,
	".mpeg":  Video,
	".mpg":   Video,
	".mpv":   Video,
	".mxf":   Video,
	".nsv":   Video,
	".ogg":   Video,
	".ogm":   Video,
	".ogv":   Video,
	".qt":    Video,
	".rm":    Video,
	".rmvb":  Video,
	".roq":   Video,
	".srt":   Video,
	".svi":   Video,
	".vob":   Video,
	".webm":  Video,
	".wmv":   Video,
	".yuv":   Video,
}
